version: "3.1"
volumes:
    crud-books-database-data:
        driver: local
services:
    webserver:
        image: nginx:alpine
        container_name: crud-server
        working_dir: /applications
        volumes:
            - ./:/applications/crud_books
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8001:8001"
    mysql:
        image: mysql:5.7
        container_name: main-database
        volumes:
            - crud-books-database-data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=crud_book

    php-fpm82:
        build: ./
        container_name: php-fpm82
        extra_hosts:
            - host.docker.internal:host-gateway
        working_dir: /applications
        volumes:
            - ./:/applications/crud_books
        environment:
            - PHP_IDE_CONFIG=serverName=APP
